# Generated by Django 3.2.6 on 2023-06-05 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargotype',
            fields=[
                ('cargotype', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Тип груза')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sku', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Артикул')),
                ('count', models.IntegerField(verbose_name='Количество товара на складе')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
                ('types', models.ManyToManyField(related_name='item_types', to='core.Cargotype', verbose_name='Типы грузов')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Код заказа')),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('formed', 'Formed')], max_length=50, verbose_name='Статус')),
                ('items', models.ManyToManyField(related_name='order_items', to='core.Item', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('carton_type', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Тип упаковки')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота')),
                ('display_rf_pack', models.BooleanField(verbose_name='Отображать RF пакет')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('orders', models.ManyToManyField(related_name='package_orders', to='core.Order', verbose_name='Заказы')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='order_packages', to='core.Package', verbose_name='Упаковки'),
        ),
        migrations.AddField(
            model_name='cargotype',
            name='items',
            field=models.ManyToManyField(related_name='cargo_items', to='core.Item', verbose_name='Товары'),
        ),
    ]
