# Generated by Django 3.2.6 on 2023-06-08 09:08

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargotype',
            fields=[
                ('cargotype', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Тип груза')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Карготип',
                'verbose_name_plural': 'Карготипы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sku', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id товара')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('barcode', models.CharField(max_length=50, verbose_name='Штрихкод')),
                ('image', models.ImageField(upload_to='item_images/', verbose_name='Картинка')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('a', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина')),
                ('b', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина')),
                ('c', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id заказа')),
                ('status', django_enum.fields.EnumCharField(choices=[('ok', 'Ok'), ('formed', 'Formed'), ('fail', 'Fail'), ('in_progress', 'In Progress')], max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('carton_type', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Тип упаковки')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота')),
                ('display_rf_pack', models.BooleanField(verbose_name='Доступно на складе')),
                ('orders', models.ManyToManyField(related_name='package_orders', to='orders.Order', verbose_name='Заказы')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
            },
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.package')),
                ('orderkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Упаковка заказа',
                'verbose_name_plural': 'Упаковки заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='order_packages', to='orders.Package', verbose_name='Упаковки'),
        ),
        migrations.CreateModel(
            name='ItemCargotypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cargotype')),
            ],
            options={
                'verbose_name': 'Карготип товара',
                'verbose_name_plural': 'Карготипы товаров',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='order_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.ManyToManyField(related_name='item_types', to='orders.Cargotype', verbose_name='Карготипы'),
        ),
        migrations.AddField(
            model_name='cargotype',
            name='items',
            field=models.ManyToManyField(related_name='cargo_items', to='orders.Item', verbose_name='Товары'),
        ),
    ]
