# Generated by Django 3.2.6 on 2023-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargotype',
            name='cargotype',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Тип груза'),
        ),
    ]
